  release-and-push:
    name: Release And Push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: -1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx (and create builder instance)
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          platforms: linux/amd64,linux/arm64

      - name: Log in to Alibaba Cloud Container Registry
        uses: aliyun/acr-login@v1
        if: github.event_name == 'push'
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      - name: Fetch Current version
        id: get-current-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0

      - name: Push to Alibaba Cloud Container Registry - Standard Version
        id: build-standard
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          target: STANDARD
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/cokapp/casdoor:${{ steps.get-current-tag.outputs.tag }}
            registry.cn-hangzhou.aliyuncs.com/cokapp/casdoor:latest

      - name: Push All In One Version to Alibaba Cloud Container Registry
        id: build-allinone
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          target: ALLINONE
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/cokapp/casdoor-all-in-one:${{ steps.get-current-tag.outputs.tag }}
            registry.cn-hangzhou.aliyuncs.com/cokapp/casdoor-all-in-one:latest
